// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIsJqf_AxaRGnhAmcPBIL78yjM810ev7c',
    appId: '1:231669284581:web:2f055249c24bf7d13ade0c',
    messagingSenderId: '231669284581',
    projectId: 'remote-config-template',
    authDomain: 'remote-config-template.firebaseapp.com',
    storageBucket: 'remote-config-template.appspot.com',
    measurementId: 'G-54FM45T8XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF2cJon5H5eWQ8EbC_LjnrDLXzJw7p6Z4',
    appId: '1:231669284581:android:9ba274450fd3a8e63ade0c',
    messagingSenderId: '231669284581',
    projectId: 'remote-config-template',
    storageBucket: 'remote-config-template.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABLHFZ4t0zp2W96VNqmTTo22IRgk2xQ3U',
    appId: '1:231669284581:ios:c6219305a272ff653ade0c',
    messagingSenderId: '231669284581',
    projectId: 'remote-config-template',
    storageBucket: 'remote-config-template.appspot.com',
    iosClientId: '231669284581-d05q1rc21i0a97tlh2dnosuppc76f3tu.apps.googleusercontent.com',
    iosBundleId: 'com.flutterwings.remoteConfigFirebaseFlutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABLHFZ4t0zp2W96VNqmTTo22IRgk2xQ3U',
    appId: '1:231669284581:ios:c6219305a272ff653ade0c',
    messagingSenderId: '231669284581',
    projectId: 'remote-config-template',
    storageBucket: 'remote-config-template.appspot.com',
    iosClientId: '231669284581-d05q1rc21i0a97tlh2dnosuppc76f3tu.apps.googleusercontent.com',
    iosBundleId: 'com.flutterwings.remoteConfigFirebaseFlutterTemplate',
  );
}
